// import barley from './Barley.png'
// import canola from './Canola.png'
// import corn from './Corn.png'
// import oats from './Oats.png'
// import soybeans from './Soybeans.png'
// import wheat from './Wheat.png'
// import filter from './icons/ic_filter.svg'
// import search from './icons/ic_search.svg'
export { default as Barley } from './Barley.png'
export { default as Canola } from './Canola.png'
export { default as Corn } from './Corn.png'
export { default as Oats } from './Oats.png'
export { default as SoyBeans } from './Soybeans.png'
export { default as Wheat } from './Wheat.png'

export { ReactComponent as FilterIcon } from './icons/ic_filter.svg'
export { ReactComponent as Search } from './icons/ic_search.svg'
// export default { barley, canola, corn, oats, soybeans, wheat, filter, search }
